[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rppal = "0.15.0"
common = { path = "../common" }
